name: Deploy Website via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      # แก้ไขคำเตือนเรื่อง Node.js 20
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /site/wwwroot/ton/banner-cms/
        # สำหรับ Azure Port 990 ให้ใช้ protocol: ftps เท่านั้น
        protocol: ftps
        port: 990
        # ถ้ายัง Timeout ให้เพิ่มบรรทัดนี้ (หน่วยเป็นมิลลิวินาที)
        timeout: 60000
